// Generated by CoffeeScript 1.9.3
var express, router;

express = require('express');

router = express.Router();

router.get('/letters', function(req, res, next) {
  return res.sendfile('./public/letters.json');
});

router.get('*', function(req, res, next) {
  return res.render('index', {
    title: 'Typewriter'
  });
});

module.exports = router;
